### ISSUE TITLE
Implement stdin in checkpoints

### ISSUE THREAD

**Issue by tjb1982** [tjb1982/linen#5]
We currently have something like 

```yaml
checkpoint:
  nodes:
  - out: VAR1
    err: VAR2
  source: echo foo
```

but it might be interesting to have something like

```yaml
checkpoint:
  nodes:
  - out: VAR1
    in: |
      foo
      bar
      baz
      quux
    source: grep "^b"
```

where this would be functionally equivalent to

```echo "..." | grep "^b"```
